export const FETCH_BLOG_DATA_SUCCESS = 'FETCH_BLOG_DATA_SUCCESS';
export const FETCH_BLOG_DATA_FAIL = 'FETCH_BLOG_DATA_FAIL';


export const FETCH_QUOTE_DATA_SUCCESS = 'FETCH_QUOTE_DATA_SUCCESS';
export const FETCH_QUOTE_DATA_FAIL = 'FETCH_QUOTE_DATA_FAIL';

export const FETCH_GALLERY_DATA_SUCCESS = 'FETCH_GALLERY_DATA_SUCCESS';
export const FETCH_GALLERY_DATA_FAIL = 'FETCH_GALLERY_DATA_FAIL';

export const POST_BLOG = 'POST_BLOG';
export const POST_BLOG_SUCCESS = 'POST_BLOG_SUCCESS';

export const CHANGE_ADMIN_STATE = 'CHANGE_ADMIN_STATE';
export const CHANGE_IMAGE_UPLOAD = 'CHANGE_IMAGE_UPLOAD';
export const UPDATE_UPLOADED_IMAGES = 'UPDATE_UPLOADED_IMAGES';