export const FETCH_BLOG_DATA_SUCCESS = 'FETCH_BLOG_DATA_SUCCESS';
export const FETCH_BLOG_DATA_FAIL = 'FETCH_BLOG_DATA_FAIL';


export const FETCH_QUOTE_DATA_SUCCESS = 'FETCH_QUOTE_DATA_SUCCESS';
export const FETCH_QUOTE_DATA_FAIL = 'FETCH_QUOTE_DATA_FAIL';

export const FETCH_GALLERY_DATA_SUCCESS = 'FETCH_GALLERY_DATA_SUCCESS';
export const FETCH_GALLERY_DATA_FAIL = 'FETCH_GALLERY_DATA_FAIL';